PruebaTecnica/Controllers/ClientesController.cs
using Newtonsoft.Json;
using PruebaTecnica.Helper;
using PruebaTecnica.Models;
using System;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IConnectionWebApi _connectionWebApi;

        public ClientesController()
        {
            _connectionWebApi = new ConnectionToWebService();
        }

        // GET: Clientes
        public async Task<ActionResult> Index()
        {
            var data = await _connectionWebApi.HttpGetAll<Cliente>("Clientes/GetCustomers", "get").ConfigureAwait(false);
            return View(data);
        }

        // GET: Clientes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Cliente>("Clientes/GetCustomerById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Create()
        {
            return View();
        }
        // POST: Clientes/Create
        [HttpPost]
        public async Task<ActionResult> Create(Cliente cliente)
        {
            cliente.IdEstado = 1;
            await _connectionWebApi.HttpPost<Cliente>("Clientes/AddCustomer", cliente, "Post").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Cliente>("Clientes/GetCustomerById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Cliente cliente)
        {
            cliente.IdEstado = 1;
            await _connectionWebApi.HttpPost<Cliente>("Clientes/UpdateCustomer/" + id, cliente, "Put").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(int id = 0)
        {
            var result = await _connectionWebApi.HttpGetBy<Cliente>("Clientes/GetCustomerById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Cliente cliente, int id = 0)
        {
            await _connectionWebApi.HttpPost<Cliente>("Clientes/RemoveCustomer/" + id, new object(), "Delete").ConfigureAwait(false);
            return RedirectToAction("Index");

        }
    }
}

PruebaTecnica/Controllers/CuotasController.cs
using PruebaTecnica.Helper;
using PruebaTecnica.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class CuotasController : Controller
    {
        private readonly IConnectionWebApi _connectionWebApi;

        public CuotasController()
        {
            _connectionWebApi = new ConnectionToWebService();
        }
        // GET: Cuotas
        public async Task<ActionResult> Index()
        {
            var data = await _connectionWebApi.HttpGetAll<Cuota>("Cuotas/GetAllFees", "get").ConfigureAwait(false);
            return View(data);
        }

        // GET: Cuotas/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Cuota>("Cuotas/GetFeeById/" + id, "get").ConfigureAwait(false);
            return View();
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Create()
        {
            return View();
        }
        // POST: Clientes/Create
        [HttpPost]
        public async Task<ActionResult> Create(Cuota cuota)
        {
            cuota.IdEstado = 1;
            await _connectionWebApi.HttpPost<Cuota>("Cuotas/AddFee", cuota, "Post").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Cuota>("Cuotas/GetFeeById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Cuota cuota)
        {
            cuota.IdEstado = 1;
            await _connectionWebApi.HttpPost<Cuota>("Cuotas/UpdateFee/" + id, cuota , "Put").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(int id = 0)
        {
            var result = await _connectionWebApi.HttpGetBy<Cuota>("Cuotas/GetFeeById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Cuota cuota, int id = 0)
        {
            await _connectionWebApi.HttpPost<Cuota>("Cuotas/RemoveFee/" + id, new object(), "Delete").ConfigureAwait(false);
            return RedirectToAction("Index");

        }
    }
}

PruebaTecnica/Controllers/EstadosController.cs
using Newtonsoft.Json;
using PruebaTecnica.Helper;
using PruebaTecnica.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class EstadosController : Controller
    {
        private readonly IConnectionWebApi _connectionWebApi;

        public EstadosController()
        {
            _connectionWebApi = new ConnectionToWebService();
        }
        // GET: Estados
        public async Task<ActionResult> Index()
        {
            var data = await _connectionWebApi.HttpGetAll<Estado>("Estadoes/GetAllStatus", "get").ConfigureAwait(false);

            return View(data);
        }

        // GET: Estadoes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Estado>("Estadoes/GetStatusById/" + id, "get").ConfigureAwait(false);
            return View();
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Create()
        {
            return View();
        }
        // POST: Clientes/Create
        [HttpPost]
        public async Task<ActionResult> Create(Estado estado)
        {
            estado.IdEstado = 1;
            await _connectionWebApi.HttpPost<Estado>("Estadoes/AddStatus", estado, "Post").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Estado>("Estadoes/GetStatusById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Estado estado)
        {
            estado.IdEstado = 1;
            await _connectionWebApi.HttpPost<Estado>("Estadoes/UpdateStatus/" + id, estado, "Put").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(int id = 0)
        {
            var result = await _connectionWebApi.HttpGetBy<Estado>("Estadoes/GetStatusById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Estado estado, int id = 0)
        {
            await _connectionWebApi.HttpPost<Estado>("Estadoes/RemoveStatus/" + id, new object(), "Delete").ConfigureAwait(false);
            return RedirectToAction("Index");

        }
    }
}

PruebaTecnica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PruebaTecnica/Controllers/PagosController.cs
using PruebaTecnica.Helper;
using PruebaTecnica.Models;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class PagosController : Controller
    {
        private readonly IConnectionWebApi _connectionWebApi;

        public PagosController()
        {
            _connectionWebApi = new ConnectionToWebService();
        }
        // GET: Pagos
        public async Task<ActionResult> Index()
        {
            var data = await _connectionWebApi.HttpGetAll<Pago>("Pagoes/GetAllPayments", "get").ConfigureAwait(false);

            return View(data);
        }

        // GET: Pagoes/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Pago>("Pagoes/GetPaymentById/" + id, "get").ConfigureAwait(false);
            return View();
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Create()
        {
            return View();
        }
        // POST: Clientes/Create
        [HttpPost]
        public async Task<ActionResult> Create(Pago pago)
        {
            pago.IdEstado = 1;
            await _connectionWebApi.HttpPost<Pago>("Pagoes/AddPayment", pago, "Post").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var result = await _connectionWebApi.HttpGetBy<Pago>("Pagoes/GetPaymentById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Pago pago)
        {
            pago.IdEstado = 1;
            await _connectionWebApi.HttpPost<Pago>("Pagoes/UpdatePayment/" + id, pago, "Put").ConfigureAwait(false);
            return RedirectToAction("Index");
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> Delete(int id = 0)
        {
            var result = await _connectionWebApi.HttpGetBy<Pago>("Pagoes/GetPaymentById/" + id, "get").ConfigureAwait(false);
            return View(result);
        }

        // POST: Clientes/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(Pago pago, int id = 0)
        {
            await _connectionWebApi.HttpPost<Pago>("Pagoes/RemovePayment/" + id, new object(), "Delete").ConfigureAwait(false);
            return RedirectToAction("Index");

        }
    }
}

PruebaTecnica/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PruebaTecnica/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PruebaTecnica/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Consominios.com</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin in orci at metus congue ultricies. Nulla ullamcorper lacus vel nisi sollicitudin, id ornare magna bibendum. Sed viverra diam sed luctus lobortis. Donec eget facilisis tellus, ac laoreet felis. Nulla facilisi. Vestibulum vitae enim ultricies risus lobortis feugiat. Maecenas vitae lectus nec neque fermentum tristique quis a augue. Donec lacinia nunc leo. Fusce feugiat gravida eros id ullamcorper.</p>
    
</div>

<div class="row">
    <div class="col-md-2">
        <a href="@Url.Action("Index", "Clientes")" class="btn btn-primary">
            <img src="https://image.flaticon.com/icons/png/512/2942/2942789.png" height="64px" width="64px" alt="Alternate Text" /> <br />
            <span>
                <strong>Clientes</strong>
            </span>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Index", "Residenciales")" class="btn btn-primary">
            <img src="https://image.flaticon.com/icons/png/512/619/619153.png" height="64px" width="64px" alt="Alternate Text" /> <br />
            <span>
                <strong>Condominio</strong>
            </span>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Index", "Pagos")" class="btn btn-primary">
            <img src="https://image.flaticon.com/icons/png/512/951/951764.png" height="64px" width="64px" alt="Alternate Text" /> <br />
            <span>
                <strong>Pagos</strong>
            </span>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Index", "Cuotas")" class="btn btn-primary">
            <img src="https://image.flaticon.com/icons/png/512/1019/1019607.png" height="64px" width="64px" alt="Alternate Text" /> <br />
            <span>
                <strong>Cuotas</strong>
            </span>
        </a>
    </div>
    <div class="col-md-2">
        <a href="@Url.Action("Index", "Estados")" class="btn btn-primary">
            <img src="https://image.flaticon.com/icons/png/512/718/718970.png" height="64px" width="64px" alt="Alternate Text" /> <br />
            <span>
                <strong>Estados</strong>
            </span>
        </a>
    </div>
</div>